


% plot_figure4.m
clc; clear; close all;

% --- Load the REAL data generated by the AO algorithm ---
try
    load('fig4_results.mat');
    fprintf('Successfully loaded fig4_results.mat\n');
catch
    error('Could not find fig4_results.mat. Please run main_script_for_figures.m first.');
end

% --- Extract Data ---
M_values = fig4_results.M_range;
rate_PS = fig4_results.PS.rates;
snr_PS = fig4_results.PS.snrs;
rate_PS_RL1 = fig4_results.PS_RL1.rates;
snr_PS_RL1 = fig4_results.PS_RL1.snrs;
rate_PS_RL2 = fig4_results.PS_RL2.rates;
snr_PS_RL2 = fig4_results.PS_RL2.snrs;

% --- Plotting ---
figure('Position', [100, 100, 800, 700]);

% Top plot: Average sum-rate
subplot(2,1,1);
hold on; box on; grid on;
plot(M_values, rate_PS_RL2, '^-', 'LineWidth', 2, 'MarkerSize', 7, 'DisplayName', 'PS-RL2 (RIS near CUs)');
plot(M_values, rate_PS,     'o-', 'LineWidth', 2, 'MarkerSize', 7, 'DisplayName', 'PS (Default)');
plot(M_values, rate_PS_RL1, 's-', 'LineWidth', 2, 'MarkerSize', 7, 'DisplayName', 'PS-RL1 (RIS near Target)');
ylabel("Avg. Sum-Rate (bits/s/Hz)", 'FontWeight', 'bold');
title('System Performance vs. Number of RIS Elements (M)', 'FontWeight', 'bold');
legend('Location', 'southeast');
set(gca, 'FontSize', 10);

% Bottom plot: Sensing SNR
subplot(2,1,2);
hold on; box on; grid on;
plot(M_values, snr_PS_RL1, 's-', 'LineWidth', 2, 'MarkerSize', 7, 'DisplayName', 'PS-RL1 (RIS near Target)');
plot(M_values, snr_PS,     'o-', 'LineWidth', 2, 'MarkerSize', 7, 'DisplayName', 'PS (Default)');
plot(M_values, snr_PS_RL2, '^-', 'LineWidth', 2, 'MarkerSize', 7, 'DisplayName', 'PS-RL2 (RIS near CUs)');
ylabel("Avg. Sensing SNR (dB)", 'FontWeight', 'bold');
xlabel("Number of RIS Passive Elements (M)", 'FontWeight', 'bold');
legend('Location', 'southeast');
set(gca, 'FontSize', 10);





















% % plot_figure4.m
% % Loads simulation results from fig4_results.mat and plots Figure 4.
% 
% clear; close all; clc;
% % addpath(genpath('.')); % Assuming utils.m is in path if needed
% 
% output_folder = 'figures_output';
% if ~exist(output_folder, 'dir')
%     mkdir(output_folder);
% end
% 
% fprintf('Attempting to plot Figure 4: Performance vs. M...\n');
% if exist('fig4_results.mat', 'file')
%     load('fig4_results.mat'); % Loads fig4_results struct
% 
%     M_values = fig4_results.M_values;
%     beta_C_fixed_val = fig4_results.beta_C_fixed;
% 
%     plot_schemes_fig4 = {'PS', 'PS_RL1', 'PS_RL2'}; % Schemes in the paper's Figure 4
%     colors_fig4 = {
%         [0, 0.4470, 0.7410],  % Blue (PS)
%         [0.8500, 0.3250, 0.0980],  % Orange (PS-RL1)
%         [0.4660, 0.6740, 0.1880]   % Green (PS-RL2)
%     };
%     line_styles_rate = {'-o', '-s', '-^'}; % For sum-rate
%     line_styles_snr = {'--o', '--s', '--^'}; % For sensing SNR (differentiated)
%     
%     % --- Figure 4a: Sum-Rate vs M ---
%     figure('Name', 'Figure 4a: Sum-Rate vs. M', 'Position', [200, 200, 700, 550]);
%     hold on; grid on; box on;
%     
%     for i = 1:length(plot_schemes_fig4)
%         scheme_name = plot_schemes_fig4{i};
%         if isfield(fig4_results, scheme_name) && isfield(fig4_results.(scheme_name), 'rates')
%              plot(M_values, fig4_results.(scheme_name).rates, line_styles_rate{i}, ...
%                  'Color', colors_fig4{i}, 'LineWidth', 2, 'MarkerSize', 7, ...
%                  'MarkerFaceColor', colors_fig4{i}*0.9, ...
%                  'DisplayName', strrep(scheme_name, '_', '-'));
%         else
%             fprintf('Warning: Rate data for scheme %s not found in fig4_results.mat\n', scheme_name);
%         end
%     end
%     xlabel('Number of RIS Passive Elements (M)', 'FontSize', 12);
%     ylabel('CUs Average Sum-Rate (bits/s/Hz)', 'FontSize', 12);
%     title(sprintf('Sum-Rate vs. M (β_C = %.1f) (Fig 4a Recreation)', beta_C_fixed_val), 'FontSize', 14);
%     legend('show', 'Location', 'SouthEast', 'FontSize', 10);
%     grid on;
%     set(gca, 'FontSize', 11);
%     xticks(M_values); % Ensure all M_values are ticks
% 
%     saveas(gcf, fullfile(output_folder, 'Figure4a_SumRate_vs_M.png'));
%     saveas(gcf, fullfile(output_folder, 'Figure4a_SumRate_vs_M.fig'));
%     fprintf('Figure 4a saved to %s folder.\n', output_folder);
% 
%     % --- Figure 4b: Sensing SNR vs M ---
%     figure('Name', 'Figure 4b: Sensing SNR vs. M', 'Position', [250, 250, 700, 550]);
%     hold on; grid on; box on;
%     
%     for i = 1:length(plot_schemes_fig4)
%         scheme_name = plot_schemes_fig4{i};
%         if isfield(fig4_results, scheme_name) && isfield(fig4_results.(scheme_name), 'snrs_dB')
%             plot(M_values, fig4_results.(scheme_name).snrs_dB, line_styles_snr{i}, ...
%                  'Color', colors_fig4{i}, 'LineWidth', 2, 'MarkerSize', 7, ...
%                  'MarkerFaceColor', colors_fig4{i}*0.9, ...
%                  'DisplayName', strrep(scheme_name, '_', '-'));
%         else
%              fprintf('Warning: Sensing SNR data for scheme %s not found in fig4_results.mat\n', scheme_name);
%         end
%     end
%     xlabel('Number of RIS Passive Elements (M)', 'FontSize', 12);
%     ylabel('Average Sensing SNR (dB)', 'FontSize', 12);
%     title(sprintf('Sensing SNR vs. M (β_C = %.1f) (Fig 4b Recreation)', beta_C_fixed_val), 'FontSize', 14);
%     legend('show', 'Location', 'SouthEast', 'FontSize', 10);
%     grid on;
%     set(gca, 'FontSize', 11);
%     xticks(M_values);
% 
%     saveas(gcf, fullfile(output_folder, 'Figure4b_SensingSNR_vs_M.png'));
%     saveas(gcf, fullfile(output_folder, 'Figure4b_SensingSNR_vs_M.fig'));
%     fprintf('Figure 4b saved to %s folder.\n', output_folder);
% else
%     warning('fig4_results.mat not found. Run main_script_for_figures.m first to generate data.');
% end
% 
% fprintf('Individual figure plotting complete.\n');
% 





% % plot_figure4.m
% function plot_figure4()
%     load('fig4_results.mat', 'fig4_results');
%     
%     M_range = fig4_results.M_range;
%     
%     figure;
%     
%     % Plot for Communication Rate
%     yyaxis left;
%     hold on;
%     plot(M_range, fig4_results.PS_RL2.rates, '-^', 'Color', 'r', 'LineWidth', 1.5, 'DisplayName', 'PS-RL2 (Rate)');
%     plot(M_range, fig4_results.PS.rates, '-o', 'Color', 'b', 'LineWidth', 1.5, 'DisplayName', 'PS (Rate)');
%     plot(M_range, fig4_results.PS_RL1.rates, '-s', 'Color', 'g', 'LineWidth', 1.5, 'DisplayName', 'PS-RL1 (Rate)');
%     ylabel('CUs'' Average Sum-Rate (bits/s/Hz)');
%     ax = gca;
%     ax.YColor = 'k';
%     
%     % Plot for Sensing SNR
%     yyaxis right;
%     hold on;
%     plot(M_range, fig4_results.PS_RL2.snrs, '--^', 'Color', 'r', 'LineWidth', 1.5, 'DisplayName', 'PS-RL2 (SNR)');
%     plot(M_range, fig4_results.PS.snrs, '--o', 'Color', 'b', 'LineWidth', 1.5, 'DisplayName', 'PS (SNR)');
%     plot(M_range, fig4_results.PS_RL1.snrs, '--s', 'Color', 'g', 'LineWidth', 1.5, 'DisplayName', 'PS-RL1 (SNR)');
%     ylabel('Average Sensing SNR (dB)');
%     ax = gca;
%     ax.YColor = 'k';
%     
%     hold off;
%     box on;
%     grid on;
%     title('Performance vs. Number of RIS Elements (\beta_C = 0.5)');
%     xlabel('Number of RIS Passive Elements, M');
%     legend('show', 'Location', 'Best');
%     
%     % Save the figure
%     if ~exist('figures_output', 'dir')
%        mkdir('figures_output')
%     end
%     saveas(gcf, 'figures_output/figure4_perf_vs_m.png');
% end