
%plot_figure2.m
clc; clear; close all;

% --- Load the REAL data generated by the AO algorithm ---
try
    load('fig2_results.mat');
    fprintf('Successfully loaded fig2_results.mat\n');
catch
    error('Could not find fig2_results.mat. Please run main_script_for_figures.m first.');
end

% --- Extract Static Point Locations from the loaded data ---
% This ensures the plot matches the simulation parameters
plot_info = fig2_results.plot_info;
q0 = plot_info.q0(1:2); % Use only XY for plotting
qF = plot_info.qF(1:2);
us = plot_info.u_s_3d(1:2);
uR = plot_info.u_R_pos(1:2);
CU1 = plot_info.u_k_coords_3d(1, 1:2)'; % First user's XY
CU2 = plot_info.u_k_coords_3d(2, 1:2)'; % Second user's XY

% --- Extract OPTIMIZED Trajectories from the loaded data ---
q_PS05 = fig2_results.PS_betaC_0_5.q_opt(1:2, :);
q_PS0  = fig2_results.PS_betaC_0.q_opt(1:2, :); 
q_PS1  = fig2_results.PS_betaC_1.q_opt(1:2, :);
q_NR   = fig2_results.NR_betaC_0_5.q_opt(1:2, :);

% --- Plotting (This section is copied directly from your simple script) ---
figure('Position', [100, 100, 800, 700], 'Color', 'w');
ax = axes;
hold(ax, 'on');
box(ax, 'on');
grid(ax, 'on');

% Trajectory Colors and Styles
color_NR_yellow   = [0.9290 0.6940 0.1250];
color_PS1_blue    = [0 0.4470 0.7410];
color_PS0_red     = [0.8500 0.3250 0.0980];
color_PS05_green  = [0.4660 0.6740 0.1880];
line_width_traj = 1.5;
marker_size_traj = 6;
marker_edge_color_traj = 'k';

% Plot Trajectories
plot(ax, q_PS05(1,:), q_PS05(2,:), '-d', 'Color', color_PS05_green, ...
    'MarkerFaceColor', color_PS05_green, 'MarkerEdgeColor', marker_edge_color_traj, ...
    'LineWidth', line_width_traj, 'MarkerSize', marker_size_traj, 'DisplayName', 'PS, \beta_C = 0.5');

plot(ax, q_PS0(1,:), q_PS0(2,:), '-s', 'Color', color_PS0_red, ...
    'MarkerFaceColor', color_PS0_red, 'MarkerEdgeColor', marker_edge_color_traj, ...
    'LineWidth', line_width_traj, 'MarkerSize', marker_size_traj, 'DisplayName', 'PS, \beta_C = 0');

plot(ax, q_PS1(1,:), q_PS1(2,:), '-^', 'Color', color_PS1_blue, ...
    'MarkerFaceColor', color_PS1_blue, 'MarkerEdgeColor', marker_edge_color_traj, ...
    'LineWidth', line_width_traj, 'MarkerSize', marker_size_traj, 'DisplayName', 'PS, \beta_C = 1');

plot(ax, q_NR(1,:), q_NR(2,:), '-*', 'Color', color_NR_yellow, ...
    'MarkerFaceColor', color_NR_yellow, 'MarkerEdgeColor', color_NR_yellow, ...
    'LineWidth', line_width_traj, 'MarkerSize', marker_size_traj+1, 'DisplayName', 'NR (No RIS)');

% --- Plot Static Points ---
marker_color_static_fill = '#001f3f';
static_marker_size_large = 150;
static_marker_size_medium = 200;
text_offset_y = 10;
text_offset_x = 8;

scatter(ax, us(1), us(2), static_marker_size_large, 's', 'filled', ...
    'MarkerFaceColor', marker_color_static_fill, 'MarkerEdgeColor', 'k', 'LineWidth', 1, 'HandleVisibility', 'off');
text(ax, us(1), us(2) + text_offset_y, 'Target', 'HorizontalAlignment', 'center', 'FontWeight', 'bold');

scatter(ax, uR(1), uR(2), static_marker_size_medium, 'p', 'filled', ...
    'MarkerFaceColor', marker_color_static_fill, 'MarkerEdgeColor', 'k', 'LineWidth', 1, 'HandleVisibility', 'off');
text(ax, uR(1), uR(2) - text_offset_y, 'RIS', 'HorizontalAlignment', 'center','VerticalAlignment','top', 'FontWeight', 'bold');

scatter(ax, CU1(1), CU1(2), static_marker_size_large, 'o', 'filled', ...
    'MarkerFaceColor', marker_color_static_fill, 'MarkerEdgeColor', 'k', 'LineWidth', 1, 'HandleVisibility', 'off');
text(ax, CU1(1), CU1(2) + text_offset_y, 'CU_1', 'HorizontalAlignment', 'center', 'FontWeight', 'bold');

scatter(ax, CU2(1), CU2(2), static_marker_size_large, 'o', 'filled', ...
    'MarkerFaceColor', marker_color_static_fill, 'MarkerEdgeColor', 'k', 'LineWidth', 1, 'HandleVisibility', 'off');
text(ax, CU2(1) + text_offset_x, CU2(2), 'CU_2', 'HorizontalAlignment', 'left', 'FontWeight', 'bold');

plot(ax, q0(1), q0(2), 'o', 'MarkerSize', 8, 'MarkerFaceColor', 'k', 'MarkerEdgeColor','k', 'HandleVisibility', 'off');
text(ax, q0(1), q0(2) - text_offset_y, 'Initial Point', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'top');

plot(ax, qF(1), qF(2), 'o', 'MarkerSize', 8, 'MarkerFaceColor', 'k', 'MarkerEdgeColor','k','HandleVisibility', 'off');
text(ax, qF(1), qF(2) - text_offset_y, 'Final Point', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'top');

% --- Axis Setup ---
xlabel(ax, 'x-axis (m)', 'FontWeight', 'bold');
ylabel(ax, 'y-axis (m)', 'FontWeight', 'bold');
title(ax, 'Optimized UAV Trajectories for Different Schemes', 'FontWeight', 'bold');
legend(ax, 'show', 'Location', 'SouthWest', 'FontSize', 10);
axis equal;
xlim([-20 320]);
ylim([50 300]);
set(gca, 'FontSize', 10);




