


% plot_figure4.m
clc; clear; close all;

% --- Load the REAL data generated by the AO algorithm ---
try
    load('fig4_results.mat');
    fprintf('Successfully loaded fig4_results.mat\n');
catch
    error('Could not find fig4_results.mat. Please run main_script_for_figures.m first.');
end

% --- Extract Data ---
M_values = fig4_results.M_range;
rate_PS = fig4_results.PS.rates;
snr_PS = fig4_results.PS.snrs;
rate_PS_RL1 = fig4_results.PS_RL1.rates;
snr_PS_RL1 = fig4_results.PS_RL1.snrs;
rate_PS_RL2 = fig4_results.PS_RL2.rates;
snr_PS_RL2 = fig4_results.PS_RL2.snrs;

% --- Plotting ---
figure('Position', [100, 100, 800, 700]);

% Top plot: Average sum-rate
subplot(2,1,1);
hold on; box on; grid on;
plot(M_values, rate_PS_RL2, '^-', 'LineWidth', 2, 'MarkerSize', 7, 'DisplayName', 'PS-RL2 (RIS near CUs)');
plot(M_values, rate_PS,     'o-', 'LineWidth', 2, 'MarkerSize', 7, 'DisplayName', 'PS (Default)');
plot(M_values, rate_PS_RL1, 's-', 'LineWidth', 2, 'MarkerSize', 7, 'DisplayName', 'PS-RL1 (RIS near Target)');
ylabel("Avg. Sum-Rate (bits/s/Hz)", 'FontWeight', 'bold');
title('System Performance vs. Number of RIS Elements (M)', 'FontWeight', 'bold');
legend('Location', 'southeast');
set(gca, 'FontSize', 10);

% Bottom plot: Sensing SNR
subplot(2,1,2);
hold on; box on; grid on;
plot(M_values, snr_PS_RL1, 's-', 'LineWidth', 2, 'MarkerSize', 7, 'DisplayName', 'PS-RL1 (RIS near Target)');
plot(M_values, snr_PS,     'o-', 'LineWidth', 2, 'MarkerSize', 7, 'DisplayName', 'PS (Default)');
plot(M_values, snr_PS_RL2, '^-', 'LineWidth', 2, 'MarkerSize', 7, 'DisplayName', 'PS-RL2 (RIS near CUs)');
ylabel("Avg. Sensing SNR (dB)", 'FontWeight', 'bold');
xlabel("Number of RIS Passive Elements (M)", 'FontWeight', 'bold');
legend('Location', 'southeast');
set(gca, 'FontSize', 10);









