
%plot_figure2.m
clc; clear; close all;

% --- Load the REAL data generated by the AO algorithm ---
try
    load('fig2_results.mat');
    fprintf('Successfully loaded fig2_results.mat\n');
catch
    error('Could not find fig2_results.mat. Please run main_script_for_figures.m first.');
end

% --- Extract Static Point Locations from the loaded data ---
% This ensures the plot matches the simulation parameters
plot_info = fig2_results.plot_info;
q0 = plot_info.q0(1:2); % Use only XY for plotting
qF = plot_info.qF(1:2);
us = plot_info.u_s_3d(1:2);
uR = plot_info.u_R_pos(1:2);
CU1 = plot_info.u_k_coords_3d(1, 1:2)'; % First user's XY
CU2 = plot_info.u_k_coords_3d(2, 1:2)'; % Second user's XY

% --- Extract OPTIMIZED Trajectories from the loaded data ---
q_PS05 = fig2_results.PS_betaC_0_5.q_opt(1:2, :);
q_PS0  = fig2_results.PS_betaC_0.q_opt(1:2, :); 
q_PS1  = fig2_results.PS_betaC_1.q_opt(1:2, :);
q_NR   = fig2_results.NR_betaC_0_5.q_opt(1:2, :);

% --- Plotting (This section is copied directly from your simple script) ---
figure('Position', [100, 100, 800, 700], 'Color', 'w');
ax = axes;
hold(ax, 'on');
box(ax, 'on');
grid(ax, 'on');

% Trajectory Colors and Styles
color_NR_yellow   = [0.9290 0.6940 0.1250];
color_PS1_blue    = [0 0.4470 0.7410];
color_PS0_red     = [0.8500 0.3250 0.0980];
color_PS05_green  = [0.4660 0.6740 0.1880];
line_width_traj = 1.5;
marker_size_traj = 6;
marker_edge_color_traj = 'k';

% Plot Trajectories
plot(ax, q_PS05(1,:), q_PS05(2,:), '-d', 'Color', color_PS05_green, ...
    'MarkerFaceColor', color_PS05_green, 'MarkerEdgeColor', marker_edge_color_traj, ...
    'LineWidth', line_width_traj, 'MarkerSize', marker_size_traj, 'DisplayName', 'PS, \beta_C = 0.5');

plot(ax, q_PS0(1,:), q_PS0(2,:), '-s', 'Color', color_PS0_red, ...
    'MarkerFaceColor', color_PS0_red, 'MarkerEdgeColor', marker_edge_color_traj, ...
    'LineWidth', line_width_traj, 'MarkerSize', marker_size_traj, 'DisplayName', 'PS, \beta_C = 0');

plot(ax, q_PS1(1,:), q_PS1(2,:), '-^', 'Color', color_PS1_blue, ...
    'MarkerFaceColor', color_PS1_blue, 'MarkerEdgeColor', marker_edge_color_traj, ...
    'LineWidth', line_width_traj, 'MarkerSize', marker_size_traj, 'DisplayName', 'PS, \beta_C = 1');

plot(ax, q_NR(1,:), q_NR(2,:), '-*', 'Color', color_NR_yellow, ...
    'MarkerFaceColor', color_NR_yellow, 'MarkerEdgeColor', color_NR_yellow, ...
    'LineWidth', line_width_traj, 'MarkerSize', marker_size_traj+1, 'DisplayName', 'NR (No RIS)');

% --- Plot Static Points ---
marker_color_static_fill = '#001f3f';
static_marker_size_large = 150;
static_marker_size_medium = 200;
text_offset_y = 10;
text_offset_x = 8;

scatter(ax, us(1), us(2), static_marker_size_large, 's', 'filled', ...
    'MarkerFaceColor', marker_color_static_fill, 'MarkerEdgeColor', 'k', 'LineWidth', 1, 'HandleVisibility', 'off');
text(ax, us(1), us(2) + text_offset_y, 'Target', 'HorizontalAlignment', 'center', 'FontWeight', 'bold');

scatter(ax, uR(1), uR(2), static_marker_size_medium, 'p', 'filled', ...
    'MarkerFaceColor', marker_color_static_fill, 'MarkerEdgeColor', 'k', 'LineWidth', 1, 'HandleVisibility', 'off');
text(ax, uR(1), uR(2) - text_offset_y, 'RIS', 'HorizontalAlignment', 'center','VerticalAlignment','top', 'FontWeight', 'bold');

scatter(ax, CU1(1), CU1(2), static_marker_size_large, 'o', 'filled', ...
    'MarkerFaceColor', marker_color_static_fill, 'MarkerEdgeColor', 'k', 'LineWidth', 1, 'HandleVisibility', 'off');
text(ax, CU1(1), CU1(2) + text_offset_y, 'CU_1', 'HorizontalAlignment', 'center', 'FontWeight', 'bold');

scatter(ax, CU2(1), CU2(2), static_marker_size_large, 'o', 'filled', ...
    'MarkerFaceColor', marker_color_static_fill, 'MarkerEdgeColor', 'k', 'LineWidth', 1, 'HandleVisibility', 'off');
text(ax, CU2(1) + text_offset_x, CU2(2), 'CU_2', 'HorizontalAlignment', 'left', 'FontWeight', 'bold');

plot(ax, q0(1), q0(2), 'o', 'MarkerSize', 8, 'MarkerFaceColor', 'k', 'MarkerEdgeColor','k', 'HandleVisibility', 'off');
text(ax, q0(1), q0(2) - text_offset_y, 'Initial Point', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'top');

plot(ax, qF(1), qF(2), 'o', 'MarkerSize', 8, 'MarkerFaceColor', 'k', 'MarkerEdgeColor','k','HandleVisibility', 'off');
text(ax, qF(1), qF(2) - text_offset_y, 'Final Point', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'top');

% --- Axis Setup ---
xlabel(ax, 'x-axis (m)', 'FontWeight', 'bold');
ylabel(ax, 'y-axis (m)', 'FontWeight', 'bold');
title(ax, 'Optimized UAV Trajectories for Different Schemes', 'FontWeight', 'bold');
legend(ax, 'show', 'Location', 'SouthWest', 'FontSize', 10);
axis equal;
xlim([-20 320]);
ylim([50 300]);
set(gca, 'FontSize', 10);




% % plot_figure2.m
% % Loads simulation results from fig2_results.mat and plots Figure 2.
% 
% clear; close all; clc;
% % addpath(genpath('.')); % Assuming utils.m is in path if needed by any helper
% 
% output_folder = 'figures_output';
% if ~exist(output_folder, 'dir')
%     mkdir(output_folder);
% end
% 
% fprintf('Attempting to plot Figure 2: UAV Trajectories...\n');
% if exist('fig2_results.mat', 'file')
%     load('fig2_results.mat'); % Loads fig2_results struct
% 
%     figure('Name', 'Figure 2: UAV Trajectories', 'Position', [100, 100, 750, 650]);
%     hold on; grid on; box on;
% 
%     plot_info = fig2_results.plot_info;
%     
%     % Plot Target
%     scatter(plot_info.u_s_plot(1), plot_info.u_s_plot(2), 100, 'p', 'MarkerFaceColor', 'm', 'MarkerEdgeColor', 'k', 'LineWidth', 1, 'DisplayName', 'Target'); % Magenta target
%     % Plot CUs
%     cu_colors = {[0.2 0.6 1], [0.1 0.8 0.6]}; % Light Blue, Teal
%     for k_cu = 1:size(plot_info.u_k_coords_plot,1)
%         scatter(plot_info.u_k_coords_plot(k_cu,1), plot_info.u_k_coords_plot(k_cu,2), 100, 's', ...
%                 'MarkerFaceColor', cu_colors{k_cu}, 'MarkerEdgeColor', 'k', 'LineWidth', 1, 'DisplayName', sprintf('CU%d', k_cu));
%     end
%     
%     % Plot RIS Locations
%     scatter(plot_info.u_R_plot(1), plot_info.u_R_plot(2), 120, 'h', 'MarkerFaceColor', 'g', 'MarkerEdgeColor', 'k', 'LineWidth', 1, 'DisplayName', 'RIS (PS Default)');
%     % The paper's Fig 2 shows one RIS symbol, often the 'PS' one. 
%     % RL1 and RL2 are for sensitivity, not always plotted with trajectories unless specified.
%     % If you want to show where RL1 and RL2 would be for context:
%     % scatter(plot_info.u_R_RL1(1), plot_info.u_R_RL1(2), 100, 'h', 'MarkerFaceColor', [0.7 1 0.7], 'MarkerEdgeColor', 'k', 'DisplayName', 'RIS (RL1 loc.)', 'MarkerFaceAlpha', 0.4);
%     % scatter(plot_info.u_R_RL2(1), plot_info.u_R_RL2(2), 100, 'h', 'MarkerFaceColor', [0.5 0.8 0.5], 'MarkerEdgeColor', 'k', 'DisplayName', 'RIS (RL2 loc.)', 'MarkerFaceAlpha', 0.4);
% 
%     % Plot Start and End points
%     plot(plot_info.q0(1), plot_info.q0(2), 'ko', 'MarkerSize', 8, 'MarkerFaceColor', 'k', 'DisplayName', 'Start Point');
%     text(plot_info.q0(1)+5, plot_info.q0(2), 'Initial Point', 'FontSize', 9);
%     plot(plot_info.qF(1), plot_info.qF(2), 'k^', 'MarkerSize', 8, 'MarkerFaceColor', 'k', 'DisplayName', 'End Point');
%     text(plot_info.qF(1)+5, plot_info.qF(2), 'Final Point', 'FontSize', 9);
% 
% 
%     % Plot PS trajectories
%     beta_C_values_fig2_plot = [0, 0.5, 1]; % As per paper's figure legend
%     line_styles_ps = {'-.', '-', '--'}; % Adjusted to match typical paper styles
%     colors_ps = {[0.8500 0.3250 0.0980], [0 0.4470 0.7410], [0.4660 0.6740 0.1880]}; % Orange, Blue, Green
% 
%     for i = 1:length(beta_C_values_fig2_plot)
%         beta_C_val = beta_C_values_fig2_plot(i);
%         field_name_q = sprintf('PS_betaC_%s', strrep(num2str(beta_C_val), '.', '_'));
%         if isfield(fig2_results, field_name_q) && isfield(fig2_results.(field_name_q), 'q_opt')
%             q_opt = fig2_results.(field_name_q).q_opt;
%             plot(q_opt(1,:), q_opt(2,:), 'LineWidth', 2, 'LineStyle', line_styles_ps{i}, 'Color', colors_ps{i}, ...
%                  'DisplayName', sprintf('PS (β_C = %.1f)', beta_C_val));
%         else
%             fprintf('Warning: Trajectory data for PS (β_C = %.1f) not found in fig2_results.mat\n', beta_C_val);
%         end
%     end
% 
%     % Plot NR trajectory (β_C = 0.5)
%     if isfield(fig2_results, 'NR_betaC_0_5') && isfield(fig2_results.NR_betaC_0_5, 'q_opt')
%         q_opt_nr = fig2_results.NR_betaC_0_5.q_opt;
%         plot(q_opt_nr(1,:), q_opt_nr(2,:), 'LineWidth', 2, 'LineStyle', ':', 'Color', [0.6350 0.0780 0.1840], ... % Dark Red, dotted
%              'DisplayName', 'NR (β_C = 0.5)');
%     else
%         fprintf('Warning: Trajectory data for NR (β_C = 0.5) not found in fig2_results.mat\n');
%     end
% 
%     xlabel('x-coordinate (m)', 'FontSize', 12);
%     ylabel('y-coordinate (m)', 'FontSize', 12);
%     title('UAV Trajectories (Figure 2 Recreation)', 'FontSize', 14);
%     legend('show', 'Location', 'EastOutside', 'FontSize', 10);
%     axis equal; 
%     grid on;
%     set(gca, 'FontSize', 11);
%     
%     % Adjust limits for better visualization based on the paper's appearance
%     xlim([-10 310]);
%     ylim([0 300]); % Based on typical Fig 2 layout
% 
%     saveas(gcf, fullfile(output_folder, 'Figure2_UAV_Trajectories.png'));
%     saveas(gcf, fullfile(output_folder, 'Figure2_UAV_Trajectories.fig'));
%     fprintf('Figure 2 saved to %s folder.\n', output_folder);
% else
%     warning('fig2_results.mat not found. Run main_script_for_figures.m first to generate data.');
% end